name: Update Telegram Subs

on:
 # schedule:
   # - cron: '0 */4 * * *' # هر ۴ ساعت به صورت خودکار
  workflow_dispatch:
    inputs:
      run_scraper:
        description: 'Run Scraper? (Download Messages)'
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 pyyaml lxml

    - name: 1. Run Scraper (Download Messages)
      # این مرحله فقط اگر اجرای خودکار باشد یا در اجرای دستی تیک خورده باشد اجرا می‌شود
      if: github.event_name == 'schedule' || inputs.run_scraper == true
      run: python src/telegram_scraper.py

    - name: 2. Run Extractor (Process Configs)
      # این مرحله همیشه اجرا می‌شود
      run: python src/config_extractor.py

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Auto-update: Archives & Subs [skip ci]"
        file_pattern: 'src/telegram/* sub/*'
