name: Update Telegram Subs

on:
#  schedule:
   # - cron: '0 */4 * * *' # هر ۴ ساعت
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 pyyaml lxml

    - name: 1. Run Scraper (Download Messages)
      run: python src/telegram_scraper.py

    - name: 2. Run Extractor (Process Configs)
      run: python src/config_extractor.py

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Auto-update: Archives & Subs [skip ci]"
        file_pattern: 'src/telegram/* sub/*'
